# Generated by Django 4.2 on 2024-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('del_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
            ],
        ),
    ]
